// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UAMS.Room.Presistence;

#nullable disable

namespace UAMS.Room.Migrations
{
    [DbContext(typeof(RoomDesignDbContext))]
    [Migration("20260522140026_Integration-With-Vk")]
    partial class IntegrationWithVk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("RoomDesign")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UAMS.Room.Models.AssetDefenetion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("AllowedLocations")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("AssetAllowedLocations");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SvgUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("AssetDefinitions", "RoomDesign");
                });

            modelBuilder.Entity("UAMS.Room.Models.ChecklistItemTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AssetDefinitionId");

                    b.ToTable("ChecklistItemTemplates", "RoomDesign");
                });

            modelBuilder.Entity("UAMS.Room.Models.PlacedAssetChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlacedAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("StudyYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("PlacedAssetChecklists", "RoomDesign");
                });

            modelBuilder.Entity("UAMS.Room.Models.PlacedAssetChecklistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetChecklistId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CheckedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChecklistItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AssetChecklistId");

                    b.HasIndex("ChecklistItemId");

                    b.ToTable("PlacedAssetChecklistEntries", "RoomDesign");
                });

            modelBuilder.Entity("UAMS.Room.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClosureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("DesignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Rooms", "RoomDesign");
                });

            modelBuilder.Entity("UAMS.Room.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedMaintainerVkId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MaintainerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlacedAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VkNotificationStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("PlacedAssetId")
                        .IsUnique()
                        .HasFilter("\"Status\" NOT IN (8, 9, 10, 11)");

                    b.HasIndex("ReporterId");

                    b.ToTable("Tickets", "RoomDesign");
                });

            modelBuilder.Entity("UAMS.Room.Models.TicketNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketNotes", "RoomDesign");
                });

            modelBuilder.Entity("UAMS.Room.Models.ChecklistItemTemplate", b =>
                {
                    b.HasOne("UAMS.Room.Models.AssetDefenetion", "AssetDefenetion")
                        .WithMany("ChecklistTemplate")
                        .HasForeignKey("AssetDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetDefenetion");
                });

            modelBuilder.Entity("UAMS.Room.Models.PlacedAssetChecklistEntry", b =>
                {
                    b.HasOne("UAMS.Room.Models.PlacedAssetChecklist", "AssetChecklist")
                        .WithMany("Entries")
                        .HasForeignKey("AssetChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UAMS.Room.Models.ChecklistItemTemplate", "ChecklistItem")
                        .WithMany()
                        .HasForeignKey("ChecklistItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetChecklist");

                    b.Navigation("ChecklistItem");
                });

            modelBuilder.Entity("UAMS.Room.Models.Room", b =>
                {
                    b.OwnsOne("UAMS.Room.Models.RoomLayout", "Layout", b1 =>
                        {
                            b1.Property<Guid>("RoomId1");

                            b1.Property<DateTime>("LastModifiedDate");

                            b1.Property<Guid>("LastModifiedUserId");

                            b1.Property<int>("Version");

                            b1.HasKey("RoomId1");

                            b1.ToTable("Rooms", "RoomDesign");

                            b1
                                .ToJson("Layout")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RoomId1");

                            b1.OwnsMany("UAMS.Room.Models.PlacedAssetEntry", "PlacedAssets", b2 =>
                                {
                                    b2.Property<Guid>("RoomLayoutRoomId1");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<Guid>("AssetDefinitionId");

                                    b2.Property<string>("AssetName")
                                        .IsRequired()
                                        .HasMaxLength(200);

                                    b2.Property<int>("Condition");

                                    b2.Property<Guid?>("GroupId");

                                    b2.Property<string>("GroupLabel");

                                    b2.Property<float>("Height");

                                    b2.Property<Guid>("Id");

                                    b2.Property<float>("Rotation");

                                    b2.Property<float>("Width");

                                    b2.Property<float>("X");

                                    b2.Property<float>("Y");

                                    b2.HasKey("RoomLayoutRoomId1", "__synthesizedOrdinal");

                                    b2.ToTable("Rooms", "RoomDesign");

                                    b2.WithOwner()
                                        .HasForeignKey("RoomLayoutRoomId1");
                                });

                            b1.Navigation("PlacedAssets");
                        });

                    b.Navigation("Layout")
                        .IsRequired();
                });

            modelBuilder.Entity("UAMS.Room.Models.TicketNote", b =>
                {
                    b.HasOne("UAMS.Room.Models.Ticket", null)
                        .WithMany("TicketNotes")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UAMS.Room.Models.AssetDefenetion", b =>
                {
                    b.Navigation("ChecklistTemplate");
                });

            modelBuilder.Entity("UAMS.Room.Models.PlacedAssetChecklist", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("UAMS.Room.Models.Ticket", b =>
                {
                    b.Navigation("TicketNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
